remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /Project1_bamap/Project_1.html
  Project 2: /Project2_bamap/Project_2.html
  Project 3: /Project3_bamap/Project_3.html
  Project 4: /Project4_bamap/Project_4.html
