remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /Project1_bamap/Project_1.html
  Project 2: /Project2_bamap/Project_2.html
  Project 3: /Project3_bamap/Project_3.html
  Project 4: /Project4_bamap/Project_4.html

$page_width: 4in;
$page_height: 7in;

@page {
 size; $page_width $page_height;
 -relaxed-page-width: $page_width;
 -relaxed-page-height: $page_height;
 margin: 15mm 10mm 15mm 10mm;
}
