remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /Project1_bamap/Project_1
  Project 2: /project2_sfi/project2.html
  Project 3: /project1_bamap/project1.html
  Project 4: /project1_bamap/project1.html
